version: "3"

services:
  intradata_crud_interface:
    container_name: intradata_crud_interface
    restart: always

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    build:
      context: ./
      dockerfile: ./Dockerfile

    ports:
      - 5173:5173

    networks:
      - intradata

networks:
  intradata:
    external: true
